name: raise-pr
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  raise-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: |
          echo "Changes are pushed to main branch"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base dev \
            --head main \
            --title "Auto PR from main to dev" \
            --body "This PR was created automatically by GitHub Actions."
      
          
          
    
