name: scheduled
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: "run it from branch"
        type: choice
        default: 'main'
        options:
          - 'main'
          - 'dev'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{steps.param.outputs.branch }}
    steps:
      - name: "param preparation"
        id: param
        run: |
          if [[ ${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "branch=${{ inputs.branch }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "branch=dev" >> $GITHUB_ENV
          else
            echo "No Valid Event"
            exit 0
          fi
  job2:
    needs: job1
    env:
      BRANCH: ${{ needs.job1.outputs.branch}}
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: |
          echo ${{env.BRANCH}}
          echo ${{github.event_name}}
